improved lpass handling

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -261,7 +261,11 @@ function confirmVaultAccess() {
   local lpass_version
   lpass_version=$(lpass --version)
   __task "LastPass CLI found: [$lpass_version] -- Authenticating..."
-  if ! _cmd "lpass status >/dev/null 2>&1"; then exit 1; fi
+  if ! _cmd "lpass status >/dev/null 2>&1"; then
+    printf "${OVERWRITE} ${RED}[X]  LastPass CLI found: [$lpass_version] -- Authentication failed\n"
+    printf " ${WARNING}${RED}   use "lpass login" to log into your LastPass Account.${NC}\n" 
+    exit 1
+  fi
   _task_done && printf "${GREEN} [✓] Successfully authenticated with LastPass CLI! ☕\n"
   return
 }
